// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	sqlxtx "ifoodish-store/pkg/sqlxtx"

	mock "github.com/stretchr/testify/mock"
)

// Transactioner is an autogenerated mock type for the Transactioner type
type Transactioner struct {
	mock.Mock
}

// BeginTransaction provides a mock function with given fields:
func (_m *Transactioner) BeginTransaction() (sqlxtx.TransactionFinisher, error) {
	ret := _m.Called()

	var r0 sqlxtx.TransactionFinisher
	if rf, ok := ret.Get(0).(func() sqlxtx.TransactionFinisher); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sqlxtx.TransactionFinisher)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
