// Code generated by mockery v2.9.4. DO NOT EDIT.

package userctlint

import (
	context "context"
	userent "ifoodish-store/internal/user/domain/entity"

	mock "github.com/stretchr/testify/mock"

	uservo "ifoodish-store/internal/user/domain/valueobject"
)

// MockUserUseCases is an autogenerated mock type for the UserUseCases type
type MockUserUseCases struct {
	mock.Mock
}

// AddUserAddress provides a mock function with given fields: ctx, userID, address
func (_m *MockUserUseCases) AddUserAddress(ctx context.Context, userID uservo.UserID, address userent.Address) (uservo.AddressID, error) {
	ret := _m.Called(ctx, userID, address)

	var r0 uservo.AddressID
	if rf, ok := ret.Get(0).(func(context.Context, uservo.UserID, userent.Address) uservo.AddressID); ok {
		r0 = rf(ctx, userID, address)
	} else {
		r0 = ret.Get(0).(uservo.AddressID)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uservo.UserID, userent.Address) error); ok {
		r1 = rf(ctx, userID, address)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChangePassword provides a mock function with given fields: ctx, userID, currentPassword, newPassword, newPasswordConfirm
func (_m *MockUserUseCases) ChangePassword(ctx context.Context, userID uservo.UserID, currentPassword uservo.PasswordRaw, newPassword uservo.PasswordRaw, newPasswordConfirm uservo.PasswordRaw) error {
	ret := _m.Called(ctx, userID, currentPassword, newPassword, newPasswordConfirm)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uservo.UserID, uservo.PasswordRaw, uservo.PasswordRaw, uservo.PasswordRaw) error); ok {
		r0 = rf(ctx, userID, currentPassword, newPassword, newPasswordConfirm)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetUserAddress provides a mock function with given fields: ctx, userID, addressID
func (_m *MockUserUseCases) GetUserAddress(ctx context.Context, userID uservo.UserID, addressID uservo.AddressID) (userent.RegisteredAddress, error) {
	ret := _m.Called(ctx, userID, addressID)

	var r0 userent.RegisteredAddress
	if rf, ok := ret.Get(0).(func(context.Context, uservo.UserID, uservo.AddressID) userent.RegisteredAddress); ok {
		r0 = rf(ctx, userID, addressID)
	} else {
		r0 = ret.Get(0).(userent.RegisteredAddress)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uservo.UserID, uservo.AddressID) error); ok {
		r1 = rf(ctx, userID, addressID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserAddresses provides a mock function with given fields: ctx, userID
func (_m *MockUserUseCases) GetUserAddresses(ctx context.Context, userID uservo.UserID) ([]userent.RegisteredAddress, error) {
	ret := _m.Called(ctx, userID)

	var r0 []userent.RegisteredAddress
	if rf, ok := ret.Get(0).(func(context.Context, uservo.UserID) []userent.RegisteredAddress); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]userent.RegisteredAddress)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uservo.UserID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserInfo provides a mock function with given fields: ctx, userID
func (_m *MockUserUseCases) GetUserInfo(ctx context.Context, userID uservo.UserID) (userent.RegisteredUser, error) {
	ret := _m.Called(ctx, userID)

	var r0 userent.RegisteredUser
	if rf, ok := ret.Get(0).(func(context.Context, uservo.UserID) userent.RegisteredUser); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(userent.RegisteredUser)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uservo.UserID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegisterUser provides a mock function with given fields: ctx, user, password, passwordConfirm
func (_m *MockUserUseCases) RegisterUser(ctx context.Context, user userent.User, password uservo.PasswordRaw, passwordConfirm uservo.PasswordRaw) (uservo.UserID, error) {
	ret := _m.Called(ctx, user, password, passwordConfirm)

	var r0 uservo.UserID
	if rf, ok := ret.Get(0).(func(context.Context, userent.User, uservo.PasswordRaw, uservo.PasswordRaw) uservo.UserID); ok {
		r0 = rf(ctx, user, password, passwordConfirm)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uservo.UserID)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, userent.User, uservo.PasswordRaw, uservo.PasswordRaw) error); ok {
		r1 = rf(ctx, user, password, passwordConfirm)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveUserAddress provides a mock function with given fields: ctx, userID, addressID
func (_m *MockUserUseCases) RemoveUserAddress(ctx context.Context, userID uservo.UserID, addressID uservo.AddressID) error {
	ret := _m.Called(ctx, userID, addressID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uservo.UserID, uservo.AddressID) error); ok {
		r0 = rf(ctx, userID, addressID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateUserAddress provides a mock function with given fields: ctx, userID, address
func (_m *MockUserUseCases) UpdateUserAddress(ctx context.Context, userID uservo.UserID, address userent.RegisteredAddress) error {
	ret := _m.Called(ctx, userID, address)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uservo.UserID, userent.RegisteredAddress) error); ok {
		r0 = rf(ctx, userID, address)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateUserInfo provides a mock function with given fields: ctx, user
func (_m *MockUserUseCases) UpdateUserInfo(ctx context.Context, user userent.RegisteredUser) error {
	ret := _m.Called(ctx, user)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, userent.RegisteredUser) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
